# Generated by Django 2.1.2 on 2019-11-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apage',
            options={'permissions': [('look_a_page', 'can get this A page message'), ('look_c_page', 'can look C page.')]},
        ),
    ]
